/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp amarokMediaPlayer2.xml -p amarokInterface
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "amarokInterface.h"

/*
 * Implementation of interface class OrgFreedesktopDBusIntrospectableInterface
 */

OrgFreedesktopDBusIntrospectableInterface::OrgFreedesktopDBusIntrospectableInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusIntrospectableInterface::~OrgFreedesktopDBusIntrospectableInterface()
{
}

/*
 * Implementation of interface class OrgFreedesktopDBusPropertiesInterface
 */

OrgFreedesktopDBusPropertiesInterface::OrgFreedesktopDBusPropertiesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusPropertiesInterface::~OrgFreedesktopDBusPropertiesInterface()
{
}

/*
 * Implementation of interface class OrgKdeAmarokAppInterface
 */

OrgKdeAmarokAppInterface::OrgKdeAmarokAppInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeAmarokAppInterface::~OrgKdeAmarokAppInterface()
{
}

/*
 * Implementation of interface class OrgKdeAmarokMpris2ExtensionsPlayerInterface
 */

OrgKdeAmarokMpris2ExtensionsPlayerInterface::OrgKdeAmarokMpris2ExtensionsPlayerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeAmarokMpris2ExtensionsPlayerInterface::~OrgKdeAmarokMpris2ExtensionsPlayerInterface()
{
}

/*
 * Implementation of interface class OrgMprisMediaPlayer2Interface
 */

OrgMprisMediaPlayer2Interface::OrgMprisMediaPlayer2Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgMprisMediaPlayer2Interface::~OrgMprisMediaPlayer2Interface()
{
}

/*
 * Implementation of interface class OrgMprisMediaPlayer2PlayerInterface
 */

OrgMprisMediaPlayer2PlayerInterface::OrgMprisMediaPlayer2PlayerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgMprisMediaPlayer2PlayerInterface::~OrgMprisMediaPlayer2PlayerInterface()
{
}

